/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module CodigoVerilog (
  input R,
  input B,
  input S,
  input E,
  output Energia,
  output IBB,
  output IRD,
  output IS,
  output \0_R_/_1_B 
);
  assign Energia = ((B & E) | (E & R));
  assign IS = (E & S);
  assign \0_R_/_1_B  = (B & ~ R);
  assign IBB = B;
  assign IRD = R;
endmodule
